const SUPABASE_URL='https://sbdowcielgtcfholfyry.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYXNlIiwicmVmIjoic2Jkb3djaWVsZ3RjZmhvbGZ5cnkiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc3NDY2OTA3MywiZXhwIjoyMDkwMjQ1MDczfQ.3dUuwXB8kcAbKvEWWMpvyrXhcdLx1x8x4wKxp3UY4Kk';
let session=null,data=null,allPeople=[];
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const fmtDate=value=>value?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:new Date(value).getFullYear()===new Date().getFullYear()?undefined:'numeric'}).format(new Date(value)):'—';
const splitValues=value=>String(value||'').split(/[\n,]/).map(v=>v.trim()).filter(Boolean);

function parseHash(){const p=new URLSearchParams(location.hash.slice(1));if(!p.get('access_token'))return null;return{access_token:p.get('access_token'),refresh_token:p.get('refresh_token')||'',token_type:p.get('token_type')||'bearer'};}
function sessionUser(token){try{const payload=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));return{id:payload.sub||'',email:payload.email||''};}catch{return{id:'',email:''};}}
async function login(email,password){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const body=await r.json();if(!r.ok)throw new Error(body.error_description||body.msg||'Sign-in failed');return body;}
function loginWithGoogle(){const authUrl=new URL(`${SUPABASE_URL}/auth/v1/authorize`);authUrl.searchParams.set('provider','google');authUrl.searchParams.set('redirect_to','https://www.tack.design/digital-home');authUrl.searchParams.set('prompt','select_account');location.href=authUrl.toString();}
function exclusions(){return{excludeEmails:splitValues(localStorage.getItem('tack_admin_exclude_emails')),excludeAnonymousIds:[...new Set([...splitValues(localStorage.getItem('tack_admin_exclude_ids')),localStorage.getItem('tack_site_visitor_id')].filter(Boolean))]};}
async function api(body={}){const r=await fetch('/api/admin-dashboard',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(body)});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||'Could not load Digital Home');return result;}

async function load(){setLoading(true);try{data=await api({days:Number($('#range').value),...exclusions()});render();}catch(error){if(error.message.includes('session')||error.message.includes('Sign in')){signOut();$('#login-message').textContent=error.message;}else showError(error.message);}finally{setLoading(false);}}
function setLoading(active){$('#refresh').textContent=active?'···':'↻';$('#refresh').disabled=active;}
function showError(message){$('#signals').innerHTML=`<div class="signal watch"><b>Digital Home needs attention</b><p>${esc(message)}</p></div>`;}

function render(){
  $('#updated').textContent=`Updated ${new Date(data.generatedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`;
  const s=data.summary;
  const metrics=[
    [s.websiteVisitors,'Website visitors',`${s.websitePageViews} tracked page views · selected window`],
    [s.authenticPeople,'Extension identities',`${s.anonymousPeople} anonymous · ${s.signedInPeople} signed in · selected window`],
    [s.successfulPeople,'People who generated',`${s.successfulGenerations} successful generation events · selected window`],
    [s.accounts,'Confirmed accounts',`${s.accountsCreated} created in selected window · all-time total shown`],
  ];
  $('#metric-grid').innerHTML=metrics.map(([value,label,note])=>`<article class="metric"><span class="value">${value}</span><span class="label">${label}</span><span class="note">${note}</span></article>`).join('');
  renderActivity();renderSignals();renderAcquisition();renderFunnel();allPeople=data.people;renderPeople();renderDomains();renderPlans();renderChrome();renderCreations();renderConnections();
}

function renderActivity(){const rows=data.daily;if(!rows.length){$('#activity-chart').innerHTML='<div class="empty">No authentic activity in this window.</div>';return;}const W=900,H=210,P=24,max=Math.max(1,...rows.flatMap(r=>[r.people,r.generations]));const x=i=>P+i*(W-P*2)/Math.max(1,rows.length-1),y=v=>H-P-v*(H-P*2)/max;const path=key=>rows.map((r,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(r[key]).toFixed(1)}`).join(' ');const area=`${path('people')} L${x(rows.length-1)},${H-P} L${P},${H-P} Z`;$('#activity-chart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#8fbef7" stop-opacity=".25"/><stop offset="1" stop-color="#8fbef7" stop-opacity="0"/></linearGradient></defs>${[0,.25,.5,.75,1].map(n=>`<line x1="${P}" x2="${W-P}" y1="${y(max*n)}" y2="${y(max*n)}" stroke="rgba(240,235,227,.07)"/>`).join('')}<path d="${area}" fill="url(#fill)"/><path d="${path('people')}" fill="none" stroke="#8fbef7" stroke-width="3" vector-effect="non-scaling-stroke"/><path d="${path('generations')}" fill="none" stroke="#d9c7a5" stroke-width="2" stroke-dasharray="5 5" vector-effect="non-scaling-stroke"/></svg>`;}
function renderSignals(){$('#signals').innerHTML=data.signals.map(signal=>`<article class="signal ${esc(signal.tone)}"><b>${esc(signal.title)}</b><p>${esc(signal.body)}</p></article>`).join('')||'<article class="signal"><b>Insufficient data for a pattern</b><p>No interpretation is shown until the selected window contains enough recorded product activity.</p></article>';}
function renderAcquisition(){const s=data.summary;$('#site-metric-grid').innerHTML=[[s.websiteVisitors,'Unique tracked visitors','Distinct first-party browser IDs'],[s.websitePageViews,'Page views','All recorded marketing-site loads'],[s.websiteStoreClicks||0,'Chrome Store clicks','Clicks from Tack pages to the store'],[s.websiteCtaClicks||0,'Other primary CTA clicks','Recorded primary calls to action']].map(([value,label,note])=>`<article class="metric"><span class="value">${value}</span><span class="label">${label}</span><span class="note">${note}</span></article>`).join('');const rows=(items,name,value)=>items.map(row=>`<div class="domain-row"><span>${esc(row[name])}</span><span>${row[value]}</span></div>`).join('')||'<div class="empty">No data recorded yet.</div>';$('#site-pages').innerHTML=rows(data.acquisition.pages,'path','views');$('#site-referrers').innerHTML=rows(data.acquisition.referrers,'referrer','views');}
function renderFunnel(){const max=Math.max(1,...data.funnel.map(row=>row.people));$('#funnel').innerHTML=data.funnel.map(row=>`<div class="funnel-row"><span>${esc(row.label)}</span><div class="funnel-track"><div class="funnel-fill" style="width:${Math.max(1,row.people/max*100)}%"></div></div><b>${row.people}</b><span class="funnel-rate">${row.fromOpen}%</span></div>`).join('');const a=data.activation||{returningPeople:0,repeatCreators:0,medianActivationMinutes:null,generationClicks:0,generationFailures:0,generationFailureRate:0};$('#activation-grid').innerHTML=[[a.returningPeople,'Returning extension identities','Active on two or more calendar days'],[a.repeatCreators,'Repeat creators','More than one successful generation'],[a.medianActivationMinutes==null?'—':`${a.medianActivationMinutes}m`,'Median time to first generation','From first recorded open to first success'],[`${a.generationFailureRate}%`,'Generation failure rate',`${a.generationFailures} failures across ${a.generationClicks} clicks`]].map(([value,label,note])=>`<article class="metric"><span class="value">${value}</span><span class="label">${label}</span><span class="note">${note}</span></article>`).join('');}
function renderPeople(){const q=$('#people-search').value.trim().toLowerCase();const rows=allPeople.filter(p=>!q||[p.email,p.id,...p.domains].join(' ').toLowerCase().includes(q));$('#people-count').textContent=`${rows.length} identities`;$('#people-table').innerHTML=rows.map(p=>`<tr><td><span class="person-dot ${p.signedIn?'':'anon'}"></span>${esc(p.email||'Anonymous visitor')}<small>${esc(p.id.replace(/^(user|anon):/,'').slice(0,12))}… · ${esc(p.plan)}</small></td><td>${fmtDate(p.firstSeen)}</td><td>${fmtDate(p.lastSeen)}</td><td>${p.events} events</td><td>${p.generations}</td><td>${p.domains.slice(0,3).map(d=>`<span class="domain-pill">${esc(d)}</span>`).join('')||'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No matching identities.</td></tr>';}
function renderDomains(){$('#domains').innerHTML=`<div class="panel-head"><div><p class="eyebrow">WEBSITES</p><h3>Top inspiration sources</h3></div></div>${data.domains.map(row=>`<div class="domain-row"><span>${esc(row.domain)}</span><span>${row.people} ${row.people===1?'person':'people'}</span></div>`).join('')||'<div class="empty">No website data yet.</div>'}`;}
function renderPlans(){const total=Math.max(1,data.plans.reduce((sum,p)=>sum+p.people,0));$('#plans').innerHTML=data.plans.map(p=>`<div class="plan-row"><div class="plan-label"><span>${esc(p.plan[0].toUpperCase()+p.plan.slice(1))}</span><span>${p.people}</span></div><div class="plan-bar"><i style="width:${p.people/total*100}%"></i></div></div>`).join('');}
function renderChrome(){const c=data.chrome;const rows=c.rows;const latestWeekly=[...rows].filter(r=>r.type==='weekly_users').sort((a,b)=>b.date.localeCompare(a.date))[0]?.value||0;const latestEnabled=[...rows].filter(r=>r.type==='enabled_status'&&/enabled/i.test(r.dimension)).sort((a,b)=>b.date.localeCompare(a.date))[0]?.value||0;$('#chrome-metric-grid').innerHTML=[[c.installs,'Installs','Sum in selected window'],[c.uninstalls,'Uninstalls','Sum in selected window'],[latestWeekly,'Latest weekly users','Most recent imported report'],[latestEnabled,'Latest enabled installs','Most recent imported report']].map(([value,label,note])=>`<article class="metric"><span class="value">${value}</span><span class="label">${label}</span><span class="note">${note}</span></article>`).join('');const latestRows=type=>{const matching=rows.filter(r=>r.type===type);const latest=matching.sort((a,b)=>b.date.localeCompare(a.date))[0]?.date;return matching.filter(r=>r.date===latest&&r.dimension!=='total').sort((a,b)=>b.value-a.value);};const list=items=>items.map(row=>`<div class="domain-row"><span>${esc(row.dimension)}</span><span>${row.value}</span></div>`).join('')||'<div class="empty">No imported breakdown.</div>';$('#chrome-os').innerHTML=list(latestRows('weekly_users_os'));$('#chrome-versions').innerHTML=list(latestRows('daily_users_version'));$('#chrome-status-title').textContent=c.connected?'Imported Chrome reports':'Chrome reports not imported';$('#chrome-status-copy').textContent=c.latestImport?`Most recent import: ${new Date(c.latestImport).toLocaleString()}. These values do not update until a new Chrome dashboard export is imported.`:'No Chrome aggregate reports are currently stored.';$('#chrome-import-secondary').onclick=()=>$('#chrome-files').click();}
function renderCreations(){$('#creation-grid').innerHTML=data.recentGenerations.map(g=>{const image=g.images[0];return`<article class="creation">${image?`<img src="${esc(image)}" alt="">`:'<div class="empty">No image</div>'}<div class="creation-info"><p>${esc(g.prompt||'Untitled generation')}</p><small>${esc(g.email||'Account')} · ${fmtDate(g.createdAt)}</small></div></article>`}).join('')||'<div class="empty">No authentic saved generations in this window.</div>';}
function renderConnections(){const labels={supabase:'Supabase product data',website:'Tack website tracking',chrome:'Chrome Web Store',vercel:'Vercel Analytics'};$('#connection-grid').innerHTML=Object.entries(data.sources).map(([key,source])=>`<article class="connection"><div class="connection-top"><h3>${labels[key]}</h3><span class="status ${source.status}">${source.status.replace('_',' ')}</span></div><p>${esc(source.detail)}</p>${key==='chrome'?'<button id="import-chrome">Import updated CSV reports</button>':key==='vercel'?'<a href="https://vercel.com/dashboard" target="_blank" rel="noopener">Open Vercel dashboard</a>':'<span style="color:var(--green);font-size:11px">Automatic</span>'}</article>`).join('');$('#import-chrome')?.addEventListener('click',()=>$('#chrome-files').click());}

function inferType(name,heading){const text=`${name} ${heading}`.toLowerCase();if(text.includes('uninstall'))return'uninstalls';if(text.includes('enabled'))return'enabled_status';if(text.includes('version'))return'daily_users_version';if(text.includes('weekly users')&&text.includes('os'))return'weekly_users_os';if(text.includes('weekly users'))return'weekly_users';if(text.includes('install')&&text.includes('os'))return'installs_os';return'installs';}
function csvCells(line){const cells=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'&&quoted){value+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){cells.push(value);value='';}else value+=c;}cells.push(value);return cells;}
function isoDate(raw){const match=String(raw).match(/(\d{1,2})\/(\d{1,2})\/(\d{2,4})/);if(!match)return'';const year=Number(match[3])<100?2000+Number(match[3]):Number(match[3]);return`${year}-${String(match[1]).padStart(2,'0')}-${String(match[2]).padStart(2,'0')}`;}
async function importChrome(files){let rows=[];for(const file of files){const lines=(await file.text()).trim().split(/\r?\n/);if(lines.length<3)continue;const heading=lines.shift();const headers=csvCells(lines.shift());const type=inferType(file.name,heading);for(const line of lines){const cells=csvCells(line),date=isoDate(cells[0]);if(!date)continue;for(let i=1;i<headers.length;i++)rows.push({type,date,dimension:headers.length===2?'total':headers[i],value:Number(cells[i])||0});}}if(!rows.length)throw new Error('No dated Chrome metrics were found in those files.');await api({action:'import_chrome',rows});await load();}

function signOut(){session=null;localStorage.removeItem('tack_session');$('#app').classList.add('hidden');$('#gate').classList.remove('hidden');}
function demoData(){const now=new Date(),daily=[];for(let i=29;i>=0;i--){const d=new Date(now);d.setDate(d.getDate()-i);daily.push({day:d.toISOString().slice(0,10),people:[0,1,1,2,1,3,2][i%7],generations:[0,0,1,1,0,2,1][i%7],signups:i%9===0?1:0,events:4});}return{generatedAt:now.toISOString(),summary:{websiteVisitors:31,websitePageViews:46,authenticPeople:17,anonymousPeople:11,signedInPeople:6,successfulPeople:9,successfulGenerations:12,generationRate:52.9,signups:4,accounts:6,accountsCreated:2,paidSubscribers:0,testEventsExcluded:118},daily,funnel:[['Opened',17,100],['Scanned',14,82.4],['Selected',12,70.6],['Prompted',10,58.8],['Tried generation',10,58.8],['Generated',9,52.9],['Saw signup',7,41.2],['Signed up',4,23.5]].map(([label,people,fromOpen])=>({label,people,fromOpen,event:label})),signals:[{tone:'good',title:'Observed open-to-generation rate',body:'9 of 17 extension openers recorded a successful generation (52.9%).'},{tone:'watch',title:'Selection-to-prompt difference',body:'Two observed identities selected imagery but did not record a prompt event.'},{tone:'quiet',title:'Paid accounts',body:'No confirmed, non-test accounts currently have a Pro or Studio plan.'}],acquisition:{pages:[{path:'/',views:31,visitors:24},{path:'/upgrade',views:9,visitors:7}],referrers:[{referrer:'Direct / unknown',views:28},{referrer:'google.com',views:12}]},domains:[{domain:'pinterest.com',people:9,events:61},{domain:'behance.net',people:4,events:19},{domain:'cosmos.so',people:3,events:14},{domain:'mollusksurfshop.com',people:2,events:8}],plans:[{plan:'free',people:6},{plan:'pro',people:0},{plan:'studio',people:0}],people:[{id:'anon:8f02d74ca123',email:null,plan:'anonymous',firstSeen:daily[4].day,lastSeen:now.toISOString(),events:9,generations:1,domains:['pinterest.com'],signedIn:false},{id:'user:4b98ca81b234',email:'studio@example.com',plan:'free',firstSeen:daily[9].day,lastSeen:daily[28].day,events:13,generations:2,domains:['behance.net','cosmos.so'],signedIn:true}],recentGenerations:[{id:'g1',createdAt:now.toISOString(),email:'studio@example.com',prompt:'A sculptural lamp in warm afternoon light',images:['/images/generation_bird_flower.jpg']},{id:'g2',createdAt:daily[27].day,email:'studio@example.com',prompt:'A playful citrus drink on a blue table',images:['/images/generation_citrus_drink.jpg']}],chrome:{rows:[],latestImport:null,connected:false,installs:0,uninstalls:0},sources:{supabase:{status:'live',detail:'1,555 stored events'},website:{status:'live',detail:'First-party website events'},chrome:{status:'needs_import',detail:'Chrome statistics require aggregate reports'},vercel:{status:'external',detail:'Not used as a dashboard source'}}};}
async function boot(){const hash=parseHash();const stored=JSON.parse(localStorage.getItem('tack_session')||'null');session=hash||stored;if(!session)return;try{session.user=session.user||sessionUser(session.access_token);localStorage.setItem('tack_session',JSON.stringify(session));if(hash)history.replaceState(null,'',location.pathname+location.search);$('#admin-email').textContent=session.user.email||'Tack admin';$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');await load();}catch(error){signOut();$('#login-message').textContent=error.message||'Could not open the Digital Home.';}}

$('#login-form').addEventListener('submit',async event=>{event.preventDefault();$('#login-message').textContent='';try{session=await login($('#login-email').value,$('#login-password').value);localStorage.setItem('tack_session',JSON.stringify(session));await boot();}catch(error){$('#login-message').textContent=error.message;}});
$('#google-login').addEventListener('click',loginWithGoogle);
$('#refresh').addEventListener('click',load);$('#range').addEventListener('change',load);$('#sign-out').addEventListener('click',signOut);$('#people-search').addEventListener('input',renderPeople);
$('#open-settings').addEventListener('click',()=>{$('#exclude-emails').value=localStorage.getItem('tack_admin_exclude_emails')||'';$('#exclude-ids').value=localStorage.getItem('tack_admin_exclude_ids')||'';$('#settings-dialog').showModal();});
$('#save-settings').addEventListener('click',event=>{event.preventDefault();localStorage.setItem('tack_admin_exclude_emails',$('#exclude-emails').value);localStorage.setItem('tack_admin_exclude_ids',$('#exclude-ids').value);$('#settings-dialog').close();load();});
$('#chrome-files').addEventListener('change',async event=>{try{await importChrome([...event.target.files]);}catch(error){showError(error.message);}event.target.value='';});
document.querySelectorAll('.rail nav a').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('.rail nav a').forEach(a=>a.classList.remove('active'));link.classList.add('active');}));
if(['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).has('demo')){data=demoData();$('#admin-email').textContent='demo@tack.design';$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');render();}else boot();
